export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INIT = 'AUTH_INIT';

export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAIL = 'SET_USER_FAIL';
export const SET_USER_INIT = 'SET_USER_INIT';

export const LOGOUT = 'LOGOUT';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_INIT = 'PROFILE_INIT';

export const PROFILE_CLEAR = 'PROFILE_CLEAR';

// form_hooks
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const CHECK_FORM_VALIDITY = 'CHECK_FORM_VALIDITY';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

// all profiles
export const ALL_PROFILES_SUCCESS = 'ALL_PROFILES_SUCCESS';
export const ALL_PROFILES_FAIL = 'ALL_PROFILES_FAIL';

// github repos of user
export const GITHUB_REPOS_SUCCESS = 'GITHUB_REPOS_SUCCESS';
export const GITHUB_REPOS_FAIL = 'GITHUB_REPOS_FAIL';

// post

export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_FAIL = 'POST_FAIL';
export const POST_INIT = 'POST_INIT';
export const CHANGE_LOADING = 'CHANGE_LOADING';

// single post fetch success
export const SINGLE_POST_FETCH_SUCCESS = 'SINGLE_POST_FETCH_SUCCESS';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';

//likes
export const UPDATE_LIKE = 'UPDATE_LIKE';
export const UPDATE_LIKE_FAIL = 'UPDATE_LIKE_FAIL';

// comment
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const FETCH_SINGLE_COMMENT_SUCCESS = 'FETCH_SINGLE_COMMENT_SUCCESS';
export const FETCH_SINGLE_COMMENT_FAILED = 'FETCH_SINGLE_COMMENT_FAILED';

// ADD LOCATION ON POSTS
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS';
